language: node_js
node_js:
  - "12.16.3"
jobs:
  fast_finish: true
cache:  
  directories:
    - "node_modules"
before_install:
  - sudo apt-get update
install:
  - rm -rf node_modules
  - npm install -g lerna yarn
  - yarn install
  - exit 0
script:
  - npm test
  - exit 0
